package conoha.model;

import java.util.Date;

public class AvMovie {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.imgs
     *
     * @mbggenerated
     */
    private String imgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.size
     *
     * @mbggenerated
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.attachment_name
     *
     * @mbggenerated
     */
    private String attachmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.attachment_url
     *
     * @mbggenerated
     */
    private String attachmentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.is_Delete
     *
     * @mbggenerated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.download
     *
     * @mbggenerated
     */
    private Boolean download;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.download_time
     *
     * @mbggenerated
     */
    private Date downloadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.is_show
     *
     * @mbggenerated
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column av_movie.add_date
     *
     * @mbggenerated
     */
    private Date addDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_movie
     *
     * @mbggenerated
     */
    public AvMovie(Integer id, String name, String tag, String imgs, String url, Long size, String attachmentName, String attachmentUrl, Boolean isDelete, Boolean download, Date downloadTime, Boolean isShow, Date addDate) {
        this.id = id;
        this.name = name;
        this.tag = tag;
        this.imgs = imgs;
        this.url = url;
        this.size = size;
        this.attachmentName = attachmentName;
        this.attachmentUrl = attachmentUrl;
        this.isDelete = isDelete;
        this.download = download;
        this.downloadTime = downloadTime;
        this.isShow = isShow;
        this.addDate = addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table av_movie
     *
     * @mbggenerated
     */
    public AvMovie() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.id
     *
     * @return the value of av_movie.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.id
     *
     * @param id the value for av_movie.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.name
     *
     * @return the value of av_movie.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.name
     *
     * @param name the value for av_movie.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.tag
     *
     * @return the value of av_movie.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.tag
     *
     * @param tag the value for av_movie.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.imgs
     *
     * @return the value of av_movie.imgs
     *
     * @mbggenerated
     */
    public String getImgs() {
        return imgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.imgs
     *
     * @param imgs the value for av_movie.imgs
     *
     * @mbggenerated
     */
    public void setImgs(String imgs) {
        this.imgs = imgs == null ? null : imgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.url
     *
     * @return the value of av_movie.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.url
     *
     * @param url the value for av_movie.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.size
     *
     * @return the value of av_movie.size
     *
     * @mbggenerated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.size
     *
     * @param size the value for av_movie.size
     *
     * @mbggenerated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.attachment_name
     *
     * @return the value of av_movie.attachment_name
     *
     * @mbggenerated
     */
    public String getAttachmentName() {
        return attachmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.attachment_name
     *
     * @param attachmentName the value for av_movie.attachment_name
     *
     * @mbggenerated
     */
    public void setAttachmentName(String attachmentName) {
        this.attachmentName = attachmentName == null ? null : attachmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.attachment_url
     *
     * @return the value of av_movie.attachment_url
     *
     * @mbggenerated
     */
    public String getAttachmentUrl() {
        return attachmentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.attachment_url
     *
     * @param attachmentUrl the value for av_movie.attachment_url
     *
     * @mbggenerated
     */
    public void setAttachmentUrl(String attachmentUrl) {
        this.attachmentUrl = attachmentUrl == null ? null : attachmentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.is_Delete
     *
     * @return the value of av_movie.is_Delete
     *
     * @mbggenerated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.is_Delete
     *
     * @param isDelete the value for av_movie.is_Delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.download
     *
     * @return the value of av_movie.download
     *
     * @mbggenerated
     */
    public Boolean getDownload() {
        return download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.download
     *
     * @param download the value for av_movie.download
     *
     * @mbggenerated
     */
    public void setDownload(Boolean download) {
        this.download = download;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.download_time
     *
     * @return the value of av_movie.download_time
     *
     * @mbggenerated
     */
    public Date getDownloadTime() {
        return downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.download_time
     *
     * @param downloadTime the value for av_movie.download_time
     *
     * @mbggenerated
     */
    public void setDownloadTime(Date downloadTime) {
        this.downloadTime = downloadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.is_show
     *
     * @return the value of av_movie.is_show
     *
     * @mbggenerated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.is_show
     *
     * @param isShow the value for av_movie.is_show
     *
     * @mbggenerated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column av_movie.add_date
     *
     * @return the value of av_movie.add_date
     *
     * @mbggenerated
     */
    public Date getAddDate() {
        return addDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column av_movie.add_date
     *
     * @param addDate the value for av_movie.add_date
     *
     * @mbggenerated
     */
    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    @Override
    public String toString() {
        return "AvMovie{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", tag='" + tag + '\'' +
                ", imgs='" + imgs + '\'' +
                ", url='" + url + '\'' +
                ", size=" + size +
                ", attachmentName='" + attachmentName + '\'' +
                ", attachmentUrl='" + attachmentUrl + '\'' +
                ", isDelete=" + isDelete +
                ", download=" + download +
                ", downloadTime=" + downloadTime +
                ", isShow=" + isShow +
                ", addDate=" + addDate +
                '}';
    }
}