package conoha.model;

import java.util.ArrayList;
import java.util.List;

public class PixivImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public PixivImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPixivIdIsNull() {
            addCriterion("pixiv_id is null");
            return (Criteria) this;
        }

        public Criteria andPixivIdIsNotNull() {
            addCriterion("pixiv_id is not null");
            return (Criteria) this;
        }

        public Criteria andPixivIdEqualTo(Long value) {
            addCriterion("pixiv_id =", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdNotEqualTo(Long value) {
            addCriterion("pixiv_id <>", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdGreaterThan(Long value) {
            addCriterion("pixiv_id >", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pixiv_id >=", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdLessThan(Long value) {
            addCriterion("pixiv_id <", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdLessThanOrEqualTo(Long value) {
            addCriterion("pixiv_id <=", value, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdIn(List<Long> values) {
            addCriterion("pixiv_id in", values, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdNotIn(List<Long> values) {
            addCriterion("pixiv_id not in", values, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdBetween(Long value1, Long value2) {
            addCriterion("pixiv_id between", value1, value2, "pixivId");
            return (Criteria) this;
        }

        public Criteria andPixivIdNotBetween(Long value1, Long value2) {
            addCriterion("pixiv_id not between", value1, value2, "pixivId");
            return (Criteria) this;
        }

        public Criteria andLocalPathIsNull() {
            addCriterion("local_path is null");
            return (Criteria) this;
        }

        public Criteria andLocalPathIsNotNull() {
            addCriterion("local_path is not null");
            return (Criteria) this;
        }

        public Criteria andLocalPathEqualTo(String value) {
            addCriterion("local_path =", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathNotEqualTo(String value) {
            addCriterion("local_path <>", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathGreaterThan(String value) {
            addCriterion("local_path >", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathGreaterThanOrEqualTo(String value) {
            addCriterion("local_path >=", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathLessThan(String value) {
            addCriterion("local_path <", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathLessThanOrEqualTo(String value) {
            addCriterion("local_path <=", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathLike(String value) {
            addCriterion("local_path like", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathNotLike(String value) {
            addCriterion("local_path not like", value, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathIn(List<String> values) {
            addCriterion("local_path in", values, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathNotIn(List<String> values) {
            addCriterion("local_path not in", values, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathBetween(String value1, String value2) {
            addCriterion("local_path between", value1, value2, "localPath");
            return (Criteria) this;
        }

        public Criteria andLocalPathNotBetween(String value1, String value2) {
            addCriterion("local_path not between", value1, value2, "localPath");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlIsNull() {
            addCriterion("small_image_url is null");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlIsNotNull() {
            addCriterion("small_image_url is not null");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlEqualTo(String value) {
            addCriterion("small_image_url =", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlNotEqualTo(String value) {
            addCriterion("small_image_url <>", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlGreaterThan(String value) {
            addCriterion("small_image_url >", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("small_image_url >=", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlLessThan(String value) {
            addCriterion("small_image_url <", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlLessThanOrEqualTo(String value) {
            addCriterion("small_image_url <=", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlLike(String value) {
            addCriterion("small_image_url like", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlNotLike(String value) {
            addCriterion("small_image_url not like", value, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlIn(List<String> values) {
            addCriterion("small_image_url in", values, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlNotIn(List<String> values) {
            addCriterion("small_image_url not in", values, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlBetween(String value1, String value2) {
            addCriterion("small_image_url between", value1, value2, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andSmallImageUrlNotBetween(String value1, String value2) {
            addCriterion("small_image_url not between", value1, value2, "smallImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlIsNull() {
            addCriterion("large_image_url is null");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlIsNotNull() {
            addCriterion("large_image_url is not null");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlEqualTo(String value) {
            addCriterion("large_image_url =", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlNotEqualTo(String value) {
            addCriterion("large_image_url <>", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlGreaterThan(String value) {
            addCriterion("large_image_url >", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlGreaterThanOrEqualTo(String value) {
            addCriterion("large_image_url >=", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlLessThan(String value) {
            addCriterion("large_image_url <", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlLessThanOrEqualTo(String value) {
            addCriterion("large_image_url <=", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlLike(String value) {
            addCriterion("large_image_url like", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlNotLike(String value) {
            addCriterion("large_image_url not like", value, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlIn(List<String> values) {
            addCriterion("large_image_url in", values, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlNotIn(List<String> values) {
            addCriterion("large_image_url not in", values, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlBetween(String value1, String value2) {
            addCriterion("large_image_url between", value1, value2, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andLargeImageUrlNotBetween(String value1, String value2) {
            addCriterion("large_image_url not between", value1, value2, "largeImageUrl");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("tag is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("tag is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("tag =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("tag <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("tag >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("tag >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("tag <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("tag <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("tag like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("tag not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("tag in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("tag not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("tag between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("tag not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("isDeleted is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("isDeleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(Boolean value) {
            addCriterion("isDeleted =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(Boolean value) {
            addCriterion("isDeleted <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(Boolean value) {
            addCriterion("isDeleted >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isDeleted >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(Boolean value) {
            addCriterion("isDeleted <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(Boolean value) {
            addCriterion("isDeleted <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<Boolean> values) {
            addCriterion("isDeleted in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<Boolean> values) {
            addCriterion("isDeleted not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(Boolean value1, Boolean value2) {
            addCriterion("isDeleted between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isDeleted not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pixiv_image_show
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pixiv_image_show
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}